# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-17 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='roles',
            field=models.ManyToManyField(related_name='people', to='quickstart.Role'),
        ),
    ]
